# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.AddField(
            model_name='picks',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='picks',
            name='week',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='picks',
            name='year',
            field=models.IntegerField(default=2017),
        ),
        migrations.AlterField(
            model_name='picks',
            name='is_offpick',
            field=models.BooleanField(default=False),
        ),
    ]
