# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_auto_20170910_0049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picks',
            new_name='Pick',
        ),
        migrations.RenameModel(
            old_name='Pickers',
            new_name='Picker',
        ),
    ]
