# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0003_auto_20170910_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='picker',
            name='league',
            field=models.IntegerField(default=1),
        ),
    ]
